filebeat.inputs:
  - type: filestream
    id: keycloak-logs
    enabled: true
    paths:
      - /keycloak-logs/*.log

output.logstash:
  hosts: ["logstash:5044"]

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]