input {
    beats {
        port => "5044"
    }
}
filter {

}
output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "keycloak-%{+YYYY.MM.DD}"
    }
    stdout { 
        codec => rubydebug
    }
}